### ISSUE TITLE
横瀬サウナコンセプトアイデアミーティング

### ISSUE THREAD

**Issue by LEEJIYUL** [furuhashilab/riverxsaunaxfuruhashilab#2]

**Comment by Keitaoba828** [comment]
【〇〇と川とサウナ】のアイディア出しをしましょう

**Comment by Keitaoba828** [comment]
ドローンと川とサウナ

**Comment by Keitaoba828** [comment]
みんなからもらったアイディアを共有します！
  
[古橋研究室×サウナの会場 _ handsup!.pdf](https://github.com/furuhashilab/riverxsaunaxfuruhashilab/files/4981935/x._.handsup.pdf)

**Comment by Keitaoba828** [comment]
銭湯でドローンレースしてる人がいるぞ

https://www.youtube.com/watch?v=wGff_miz3RY

**Comment by LEEJIYUL** [comment]
サウナ360度VR　レクチャー
https://vrinside.jp/news/post-177268/

**Comment by Keitaoba828** [comment]
音楽×サウナ
https://www.youtube.com/watch?time_continue=28&v=zHgMrSibuds&feature=emb_logo

**Comment by LEEJIYUL** [comment]
リモートワークと川とサウナ　（サウナ後集中力実験）

**Comment by ryuichianbo** [comment]
グッツ
↓イメージ
https://prtimes.jp/main/html/rd/p/000000036.000048312.html

**Comment by LEEJIYUL** [comment]
> グッツ
> ↓イメージ
> https://prtimes.jp/main/html/rd/p/000000036.000048312.html

古橋研究室から予算がある場合　自作でデザインしたロゴサウナタオル

**Comment by LEEJIYUL** [comment]
決定事項
ーコンセプト：川とサウナとリモートワーク　
　（サウナ後、集中力が上がるという噂を実験で検証する）　→　検証内容は動画でまとめで配信
