### ISSUE TITLE
企画書（PPT）作成

### ISSUE THREAD

**Issue by LEEJIYUL** [furuhashilab/riverxsaunaxfuruhashilab#7]

**Comment by Keitaoba828** [comment]
PPT

https://docs.google.com/presentation/d/17CAVPdQF4JY5cOp6ol_Lu-XeQ_dMs7gVCTgdut5oX5s/edit?usp=sharing

**Comment by LEEJIYUL** [comment]
大庭　担当　締め切り　7月28日　14時まで

**Comment by Keitaoba828** [comment]
提案書（企画書）完成しました！

https://drive.google.com/file/d/17ct5XyL8Y9dr3Z5B0lfNidMWPkx2WxGd/view?usp=sharing
