### ISSUE TITLE
ブログ（メディウム）作成

### ISSUE THREAD

**Issue by LEEJIYUL** [furuhashilab/riverxsaunaxfuruhashilab#9]

**Comment by LEEJIYUL** [comment]
イジユル　担当　締め切り　7月28日16時まで

**Comment by ryuichianbo** [comment]
https://medium.com/furuhashilab/%E6%A8%AA%E7%80%AC%E9%83%A8%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3-%E3%82%B3%E3%83%B3%E3%82%BB%E3%83%97%E3%83%88-d0409cd48d51

**Comment by LEEJIYUL** [comment]
https://medium.com/furuhashilab/%E6%A8%AA%E7%80%AC%E9%83%A8%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3-%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%82%B3%E3%83%B3%E3%82%BB%E3%83%97%E3%83%88-7c24e03f8300

medium link
